version: '3.5'

networks:
  net:


services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U root -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - net

  nats:
    image: nats-streaming
    container_name: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    networks:
      - net

  back:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - net
